stages:
  - pages

pages:
  image: alpine:latest
  stage: pages
  tags:
    - itup-alm-x86
  script:
    - echo "Deploying AI analysis to GitLab Pages"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
